/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// utils/date.js
var require_date = __commonJS({
  "utils/date.js"(exports2, module2) {
    function formatDate2(date) {
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, "0");
      const day = String(date.getDate()).padStart(2, "0");
      return `${year}-${month}-${day}`;
    }
    function formatDateTime2(date) {
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, "0");
      const day = String(date.getDate()).padStart(2, "0");
      const hours = String(date.getHours()).padStart(2, "0");
      const minutes = String(date.getMinutes()).padStart(2, "0");
      return `${year}-${month}-${day} ${hours}:${minutes}`;
    }
    function getWeekStartDate(date) {
      if (!(date instanceof Date) || isNaN(date.getTime())) {
        return /* @__PURE__ */ new Date();
      }
      const d = new Date(date);
      const day = d.getDay();
      const diff = d.getDate() - day + (day === 0 ? -6 : 1);
      return new Date(d.getFullYear(), d.getMonth(), diff);
    }
    function getWeekEndDate(date) {
      if (!(date instanceof Date) || isNaN(date.getTime())) {
        return /* @__PURE__ */ new Date();
      }
      const d = new Date(date);
      const day = d.getDay();
      const diff = d.getDate() - day + (day === 0 ? 0 : 7);
      return new Date(d.getFullYear(), d.getMonth(), diff);
    }
    function formatWeek(date) {
      const start = getWeekStartDate(date);
      const end = getWeekEndDate(date);
      return `${formatDate2(start)} ~ ${formatDate2(end)}`;
    }
    module2.exports = {
      formatDate: formatDate2,
      formatDateTime: formatDateTime2,
      getWeekStartDate,
      getWeekEndDate,
      formatWeek
    };
  }
});

// services/TimerManager.js
var require_TimerManager = __commonJS({
  "services/TimerManager.js"(exports2, module2) {
    var TimerManager2 = class {
      constructor() {
        this.timers = /* @__PURE__ */ new Map();
      }
      setTimeout(callback, delay) {
        const timer = setTimeout(() => {
          this.timers.delete(timer);
          Promise.resolve().then(callback).catch((error) => {
            console.error("[TimerManager] Timer callback error:", error);
          });
        }, delay);
        this.timers.set(timer, callback);
        return timer;
      }
      clearAll() {
        for (const timer of this.timers.keys()) {
          clearTimeout(timer);
        }
        this.timers.clear();
      }
      getAllTimers() {
        return Array.from(this.timers.keys());
      }
      size() {
        return this.timers.size;
      }
    };
    module2.exports = TimerManager2;
  }
});

// services/ErrorHandler.js
var require_ErrorHandler = __commonJS({
  "services/ErrorHandler.js"(exports2, module2) {
    var ErrorHandler2 = class {
      constructor(NoticeClass) {
        if (NoticeClass && typeof NoticeClass === "function") {
          this.NoticeClass = NoticeClass;
        } else {
          this.NoticeClass = null;
        }
      }
      handle(error, context = "\u672A\u77E5\u9519\u8BEF") {
        console.error(`[${context}]`, error);
        if (this.NoticeClass) {
          try {
            const notice = new this.NoticeClass(`\u64CD\u4F5C\u5931\u8D25: ${error.message}`, 5e3);
            notice.show();
          } catch (e) {
            console.error(`[${context}] \u901A\u77E5\u663E\u793A\u5931\u8D25:`, e);
          }
        }
      }
    };
    module2.exports = ErrorHandler2;
  }
});

// services/SecurityService.js
var require_SecurityService = __commonJS({
  "services/SecurityService.js"(exports2, module2) {
    var SecurityService2 = class {
      static sanitizeInput(text) {
        if (typeof text !== "string") return "";
        const div = document.createElement("div");
        div.textContent = text;
        return div.innerHTML;
      }
      static validateTaskContent(content) {
        if (!content || typeof content !== "string") {
          throw new Error("\u4EFB\u52A1\u5185\u5BB9\u4E0D\u80FD\u4E3A\u7A7A");
        }
        if (content.length > 1e3) {
          throw new Error("\u4EFB\u52A1\u5185\u5BB9\u4E0D\u80FD\u8D85\u8FC71000\u4E2A\u5B57\u7B26");
        }
        if (/<[^>]*>/.test(content)) {
          throw new Error("\u4EFB\u52A1\u5185\u5BB9\u4E0D\u80FD\u5305\u542BHTML\u6807\u7B7E");
        }
        return content.trim();
      }
      static sanitizeLink(link) {
        if (!link || typeof link !== "string") return "";
        let processedLink = link.trim();
        if (!/^https?:\/\//i.test(processedLink)) {
          processedLink = "https://" + processedLink;
        }
        try {
          const url = new URL(processedLink);
          return url.protocol === "http:" || url.protocol === "https:" ? processedLink : "";
        } catch (e) {
          return "";
        }
      }
    };
    module2.exports = SecurityService2;
  }
});

// services/ReminderService.js
var require_ReminderService = __commonJS({
  "services/ReminderService.js"(exports2, module2) {
    var { Notice } = require("obsidian");
    var ReminderService2 = class {
      constructor(timerManager, plugin) {
        this.timerManager = timerManager;
        this.plugin = plugin;
        this.reminders = /* @__PURE__ */ new Map();
        this._permissionRequested = false;
        this._visibilityHandler = null;
        this._setupVisibilityFallback();
      }
      // 请求通知权限（需在用户操作上下文中调用）
      async _requestPermission() {
        if (typeof Notification === "undefined") return "unsupported";
        if (Notification.permission === "granted") return "granted";
        if (Notification.permission === "denied") return "denied";
        if (this._permissionRequested) return Notification.permission;
        this._permissionRequested = true;
        try {
          const result = await Notification.requestPermission();
          return result;
        } catch (e) {
          return "denied";
        }
      }
      // 页面从后台恢复时，检查是否有错过的提醒
      _setupVisibilityFallback() {
        this._visibilityHandler = () => {
          if (document.hidden) return;
          const now = Date.now();
          for (const [taskId, reminder] of this.reminders) {
            if (reminder.fireAt <= now) {
              clearTimeout(reminder.timerId);
              this.reminders.delete(taskId);
              const task = this.plugin.findTaskById(taskId);
              if (task && task.completed) continue;
              const currentLink = task ? task.link : reminder.link;
              this._notify(taskId, reminder.content, currentLink);
            }
          }
          this._notifyViewsToRefresh();
        };
        document.addEventListener("visibilitychange", this._visibilityHandler);
      }
      // 设置提醒，返回 fireAt 时间戳
      async setReminder(taskId, content, delayMs, link) {
        this.cancelReminder(taskId);
        const fireAt = Date.now() + delayMs;
        const timerId = this.timerManager.setTimeout(() => {
          try {
            const task = this.plugin.findTaskById(taskId);
            if (task && task.completed) return;
            const currentLink = task ? task.link : link;
            this._notify(taskId, content, currentLink);
          } finally {
            this.reminders.delete(taskId);
            this._notifyViewsToRefresh();
          }
        }, delayMs);
        this.reminders.set(taskId, { timerId, fireAt, content, link });
        this._requestPermission();
        return fireAt;
      }
      // 更新提醒内容（不重置定时器）
      updateReminderContent(taskId, content, link) {
        const reminder = this.reminders.get(taskId);
        if (reminder) {
          reminder.content = content;
          reminder.link = link;
        }
      }
      // 取消提醒
      cancelReminder(taskId) {
        const reminder = this.reminders.get(taskId);
        if (!reminder) return false;
        clearTimeout(reminder.timerId);
        this.reminders.delete(taskId);
        return true;
      }
      // 查询是否有提醒
      hasReminder(taskId) {
        return this.reminders.has(taskId);
      }
      // 返回剩余毫秒数
      getRemainingTime(taskId) {
        const reminder = this.reminders.get(taskId);
        if (!reminder) return 0;
        return Math.max(0, reminder.fireAt - Date.now());
      }
      // 清除所有提醒
      clearAll() {
        for (const reminder of this.reminders.values()) {
          clearTimeout(reminder.timerId);
        }
        this.reminders.clear();
        if (this._visibilityHandler) {
          document.removeEventListener("visibilitychange", this._visibilityHandler);
          this._visibilityHandler = null;
        }
      }
      // 触发通知
      _notify(taskId, content, link) {
        const safeLink = link ? this._sanitizeLink(link) : null;
        if (typeof Notification !== "undefined" && Notification.permission === "granted") {
          try {
            const body = safeLink ? `${content}
${safeLink}` : content;
            const notification = new Notification("\u5F85\u529E\u63D0\u9192", { body, requireInteraction: true });
            notification.onclick = () => {
              window.focus();
              if (safeLink) window.open(safeLink, "_blank");
              notification.close();
            };
            return;
          } catch (e) {
          }
        }
        const notice = new Notice(`\u23F0 \u63D0\u9192: ${content}`, 0);
        if (safeLink) {
          const noticeEl = notice.noticeEl;
          if (noticeEl) {
            noticeEl.style.cursor = "pointer";
            noticeEl.title = safeLink;
            noticeEl.addEventListener("click", () => {
              window.open(safeLink, "_blank");
            });
          }
        } else {
          setTimeout(() => notice.hide(), 1e4);
        }
      }
      _sanitizeLink(link) {
        if (!link || typeof link !== "string") return null;
        const trimmed = link.trim();
        if (/^https?:\/\//i.test(trimmed)) return trimmed;
        return null;
      }
      // 通知视图刷新
      _notifyViewsToRefresh() {
        this.plugin.notifyViewsToRefresh();
      }
    };
    module2.exports = ReminderService2;
  }
});

// models.js
var require_models = __commonJS({
  "models.js"(exports2, module2) {
    function generateUUID() {
      if (typeof crypto !== "undefined" && crypto.randomUUID) {
        return crypto.randomUUID();
      }
      const timestamp = Date.now().toString(36);
      const randomPart = Math.random().toString(36).substring(2, 15);
      const randomPart2 = Math.random().toString(36).substring(2, 15);
      return `${timestamp}-${randomPart}-${randomPart2}`;
    }
    var PRIORITY = {
      HIGH: { value: "high", label: "\u9AD8", order: 0, color: "#ff5555" },
      MEDIUM: { value: "medium", label: "\u4E2D", order: 1, color: "#ffaa00" },
      LOW: { value: "low", label: "\u4F4E", order: 2, color: "#55aa55" },
      NONE: { value: "none", label: "\u65E0", order: 3, color: null }
    };
    function getPriorityConfig(priorityValue) {
      return Object.values(PRIORITY).find((p) => p.value === priorityValue) || PRIORITY.NONE;
    }
    function parseTags(content) {
      if (!content || typeof content !== "string") return [];
      const tagRegex = /#([\w\u4e00-\u9fa5\-_]+)/g;
      const tags = [];
      let match;
      while ((match = tagRegex.exec(content)) !== null) {
        tags.push(match[1]);
      }
      return [...new Set(tags)];
    }
    function removeTags(content) {
      if (!content || typeof content !== "string") return content;
      return content.replace(/#[\w\u4e00-\u9fa5\-_]+/g, "").replace(/\s+/g, " ").trim();
    }
    function isUrgentTask(task, todayStr) {
      if (!task.dueDate || task.completed) return false;
      if (!/^\d{4}-\d{2}-\d{2}$/.test(task.dueDate)) return false;
      const dueYear = parseInt(task.dueDate.substring(0, 4), 10);
      const dueMonth = parseInt(task.dueDate.substring(5, 7), 10);
      const dueDay = parseInt(task.dueDate.substring(8, 10), 10);
      if (dueMonth < 1 || dueMonth > 12 || dueDay < 1) return false;
      const daysInMonth = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
      const isLeapYear = dueYear % 4 === 0 && dueYear % 100 !== 0 || dueYear % 400 === 0;
      if (dueMonth === 2 && isLeapYear) {
        if (dueDay > 29) return false;
      } else if (dueDay > daysInMonth[dueMonth - 1]) {
        return false;
      }
      let prevDay = dueDay - 1;
      let prevMonth = dueMonth;
      let prevYear = dueYear;
      if (prevDay === 0) {
        prevMonth -= 1;
        if (prevMonth === 0) {
          prevMonth = 12;
          prevYear -= 1;
        }
        const daysInPrevMonth = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][prevMonth - 1];
        if (prevMonth === 2 && (prevYear % 4 === 0 && prevYear % 100 !== 0 || prevYear % 400 === 0)) {
          prevDay = 29;
        } else {
          prevDay = daysInPrevMonth;
        }
      }
      const oneDayBefore = `${prevYear}-${String(prevMonth).padStart(2, "0")}-${String(prevDay).padStart(2, "0")}`;
      return todayStr >= oneDayBefore;
    }
    module2.exports = {
      generateUUID,
      PRIORITY,
      getPriorityConfig,
      parseTags,
      removeTags,
      isUrgentTask
    };
  }
});

// modals/EditModal.js
var require_EditModal = __commonJS({
  "modals/EditModal.js"(exports2, module2) {
    var { Modal, Notice } = require("obsidian");
    var SecurityService2 = require_SecurityService();
    var ErrorHandler2 = require_ErrorHandler();
    var EditModal = class extends Modal {
      constructor(app, view, task, card, errorHandler) {
        super(app);
        this.view = view;
        this.task = task;
        this.card = card;
        this.errorHandler = errorHandler;
        this.abortController = new AbortController();
      }
      onOpen() {
        const { contentEl } = this;
        contentEl.empty();
        contentEl.createEl("h2", { text: "\u7F16\u8F91\u4EFB\u52A1" });
        const contentRow = contentEl.createEl("div", { cls: "edit-row" });
        contentRow.createEl("label", { text: "\u4EFB\u52A1\u5185\u5BB9\uFF1A" });
        const contentInput = contentRow.createEl("textarea", {
          cls: "edit-content-input"
        });
        contentInput.value = this.task.content;
        const linkRow = contentEl.createEl("div", { cls: "edit-row" });
        linkRow.createEl("label", { text: "\u94FE\u63A5\uFF1A" });
        const linkInput = linkRow.createEl("input", {
          type: "text",
          cls: "edit-input",
          value: this.task.link || "",
          placeholder: "https://..."
        });
        const dateRow = contentEl.createEl("div", { cls: "edit-row edit-row-with-date" });
        dateRow.style.cursor = "pointer";
        dateRow.createEl("label", { text: "\u622A\u6B62\u65E5\u671F\uFF1A" });
        const dateInput = dateRow.createEl("input", {
          type: "date",
          cls: "edit-input",
          value: this.task.dueDate || ""
        });
        dateRow.addEventListener("click", (e) => {
          if (e.target !== dateInput) {
            e.stopPropagation();
            setTimeout(() => {
              dateInput.focus();
              dateInput.click();
            }, 0);
          }
        }, { signal: this.abortController.signal });
        const priorityRow = contentEl.createEl("div", { cls: "edit-row" });
        priorityRow.createEl("label", { text: "\u4F18\u5148\u7EA7\uFF1A" });
        const priorityInput = priorityRow.createEl("select", { cls: "edit-input" });
        priorityInput.add(new Option("\u65E0", "none"));
        priorityInput.add(new Option("\u9AD8", "high"));
        priorityInput.add(new Option("\u4E2D", "medium"));
        priorityInput.add(new Option("\u4F4E", "low"));
        priorityInput.value = this.task.priority || "none";
        const buttonRow = contentEl.createEl("div", { cls: "edit-buttons" });
        buttonRow.createEl("button", { text: "\u4FDD\u5B58", cls: "edit-confirm-btn" }).addEventListener("click", async () => {
          const newContent = contentInput.value.trim();
          if (!newContent) {
            new Notice("\u4EFB\u52A1\u5185\u5BB9\u4E0D\u80FD\u4E3A\u7A7A", 3e3);
            return;
          }
          try {
            const validatedContent = SecurityService2.validateTaskContent(newContent);
            const safeLink = SecurityService2.sanitizeLink(linkInput.value.trim());
            this.task.content = validatedContent;
            this.task.link = safeLink || null;
            this.task.dueDate = dateInput.value || null;
            this.task.priority = priorityInput.value !== "none" ? priorityInput.value : null;
            await this.view.plugin.updateTask(this.task.taskId, this.task);
            const reminderService = this.view.plugin.reminderService;
            if (reminderService && reminderService.hasReminder(this.task.taskId)) {
              reminderService.updateReminderContent(this.task.taskId, this.task.content, this.task.link);
            }
            this.view.renderTasks();
            this.close();
          } catch (error) {
            this.errorHandler.handle(error, "\u7F16\u8F91\u4EFB\u52A1");
          }
        }, { signal: this.abortController.signal });
        buttonRow.createEl("button", { text: "\u53D6\u6D88", cls: "edit-cancel-btn" }).addEventListener("click", () => {
          this.close();
        }, { signal: this.abortController.signal });
      }
      onClose() {
        this.abortController.abort();
        const { contentEl } = this;
        contentEl.empty();
      }
    };
    module2.exports = EditModal;
  }
});

// modals/ExportModal.js
var require_ExportModal = __commonJS({
  "modals/ExportModal.js"(exports2, module2) {
    var { Modal, Notice } = require("obsidian");
    var { formatDate: formatDate2 } = require_date();
    var ExportModal = class extends Modal {
      constructor(app, view) {
        super(app);
        this.view = view;
        this.abortController = new AbortController();
      }
      onOpen() {
        const { contentEl } = this;
        contentEl.empty();
        contentEl.createEl("h2", { text: "\u5BFC\u51FA\u5F85\u529E\u4EFB\u52A1" });
        const startRow = contentEl.createEl("div", { cls: "export-row" });
        startRow.createEl("label", { text: "\u5F00\u59CB\u65E5\u671F\uFF1A" });
        const startInput = startRow.createEl("input", { type: "date", cls: "export-date-input" });
        const endRow = contentEl.createEl("div", { cls: "export-row" });
        endRow.createEl("label", { text: "\u7ED3\u675F\u65E5\u671F\uFF1A" });
        const endInput = endRow.createEl("input", { type: "date", cls: "export-date-input" });
        const today = formatDate2(/* @__PURE__ */ new Date());
        startInput.value = today;
        endInput.value = today;
        const buttonRow = contentEl.createEl("div", { cls: "export-buttons" });
        buttonRow.createEl("button", { text: "\u5BFC\u51FA", cls: "export-confirm-btn" }).addEventListener("click", () => {
          if (!startInput.value || !endInput.value) {
            new Notice("\u8BF7\u9009\u62E9\u65E5\u671F\u8303\u56F4", 3e3);
            return;
          }
          if (new Date(startInput.value) > new Date(endInput.value)) {
            new Notice("\u5F00\u59CB\u65E5\u671F\u4E0D\u80FD\u5927\u4E8E\u7ED3\u675F\u65E5\u671F", 3e3);
            return;
          }
          this.view.exportTasksToCSV(startInput.value, endInput.value);
          this.close();
        }, { signal: this.abortController.signal });
        buttonRow.createEl("button", { text: "\u53D6\u6D88", cls: "export-cancel-btn" }).addEventListener("click", () => {
          this.close();
        }, { signal: this.abortController.signal });
      }
      onClose() {
        this.abortController.abort();
        const { contentEl } = this;
        contentEl.empty();
      }
    };
    module2.exports = ExportModal;
  }
});

// views/TodoView.js
var require_TodoView = __commonJS({
  "views/TodoView.js"(exports2, module2) {
    var { ItemView, Notice, Menu, Modal } = require("obsidian");
    var { generateUUID, PRIORITY, getPriorityConfig, parseTags, removeTags, isUrgentTask } = require_models();
    var { formatDate: formatDate2, formatDateTime: formatDateTime2, getWeekStartDate, getWeekEndDate } = require_date();
    var SecurityService2 = require_SecurityService();
    var EditModal = require_EditModal();
    var ExportModal = require_ExportModal();
    var TodoView2 = class extends ItemView {
      constructor(leaf, plugin, errorHandler) {
        super(leaf);
        this.plugin = plugin;
        this.errorHandler = errorHandler;
        this.abortController = new AbortController();
        this.signal = this.abortController.signal;
        this.searchDebounceTimer = null;
        this.filterDebounceTimer = null;
      }
      getViewType() {
        return "todo-kanban-view";
      }
      getDisplayText() {
        return "\u5F85\u529E\u770B\u677F";
      }
      async onOpen() {
        var _a;
        const container = this.containerEl.children[1];
        container.empty();
        container.addClass("todo-view-container");
        this.containerEl.style.height = "100%";
        if (this.containerEl.parentElement) {
          this.containerEl.parentElement.style.height = "100%";
        }
        container.style.height = "100%";
        container.style.display = "flex";
        container.style.flexDirection = "column";
        container.style.overflow = "hidden";
        const filterSection = container.createEl("div", { cls: "todo-filter-section" });
        filterSection.style.flexShrink = "0";
        filterSection.createEl("label", { text: "\u67E5\u770B\u8303\u56F4\uFF1A", cls: "todo-filter-label" });
        this.filterSelect = filterSection.createEl("select", { cls: "todo-filter-select" });
        this.filterSelect.add(new Option("\u5F53\u65E5\u5F85\u529E", "today"));
        this.filterSelect.add(new Option("\u8FD17\u5929", "7days"));
        this.filterSelect.add(new Option("\u8FD130\u5929", "30days"));
        this.filterSelect.add(new Option("\u672C\u5468", "week"));
        this.filterSelect.add(new Option("\u5168\u90E8\u65E5\u671F", "all"));
        this.filterSelect.addEventListener("change", () => {
          clearTimeout(this.filterDebounceTimer);
          this.filterDebounceTimer = setTimeout(() => this.renderTasks(), 100);
        }, { signal: this.signal });
        filterSection.createEl("label", { text: "\u4F18\u5148\u7EA7\uFF1A", cls: "todo-filter-label" });
        this.priorityFilterSelect = filterSection.createEl("select", { cls: "todo-filter-select" });
        this.priorityFilterSelect.add(new Option("\u5168\u90E8", "all"));
        this.priorityFilterSelect.add(new Option("\u9AD8", "high"));
        this.priorityFilterSelect.add(new Option("\u4E2D", "medium"));
        this.priorityFilterSelect.add(new Option("\u4F4E", "low"));
        this.priorityFilterSelect.add(new Option("\u65E0", "none"));
        this.priorityFilterSelect.addEventListener("change", () => {
          clearTimeout(this.filterDebounceTimer);
          this.filterDebounceTimer = setTimeout(() => this.renderTasks(), 100);
        }, { signal: this.signal });
        this.searchInput = filterSection.createEl("input", {
          type: "text",
          placeholder: "\u641C\u7D22\u5F85\u529E...",
          cls: "todo-search-input"
        });
        this.searchInput.addEventListener("input", () => {
          if (this.searchDebounceTimer) {
            clearTimeout(this.searchDebounceTimer);
          }
          this.searchDebounceTimer = setTimeout(() => {
            this.renderTasks();
          }, 150);
        }, { signal: this.signal });
        const exportBtn = filterSection.createEl("button", {
          text: "\u5BFC\u51FAExcel",
          cls: "todo-export-button"
        });
        exportBtn.addEventListener("click", () => this.showExportDialog(), { signal: this.signal });
        this.tagFilterSection = container.createEl("div", { cls: "todo-tag-filter-section" });
        this.tagFilterSection.style.display = "none";
        this.tagFilterSection.createEl("label", { text: "\u6807\u7B7E\u7B5B\u9009\uFF1A", cls: "todo-filter-label" });
        this.tagFilterBadge = this.tagFilterSection.createEl("span", { cls: "todo-tag-filter-badge" });
        const clearTagBtn = this.tagFilterSection.createEl("button", {
          text: "\u6E05\u9664",
          cls: "todo-clear-tag-btn"
        });
        clearTagBtn.addEventListener("click", () => this.clearTagFilter(), { signal: this.signal });
        const tasks = ((_a = this.plugin.tasksData) == null ? void 0 : _a.tasks) || [];
        let totalTasks = 0, completedTasks = 0;
        for (const dateTask of tasks) {
          const list = dateTask.tasksList || [];
          totalTasks += list.length;
          completedTasks += list.filter((task) => task.completed === true).length;
        }
        this.taskCountBadge = filterSection.createEl("span", { cls: "todo-task-count-badge" });
        this._updateTaskCountBadge();
        this.todoContainer = container.createEl("div", { cls: "todo-container" });
        this.todoContainer.style.flex = "1 1 0";
        this.todoContainer.style.minHeight = "0";
        this.todoContainer.style.overflowY = "auto";
        this.todoContainer.style.overflowX = "hidden";
        const inputSection = container.createEl("div", { cls: "todo-input-section" });
        inputSection.style.flexShrink = "0";
        this.taskInput = inputSection.createEl("textarea", {
          placeholder: "\u8F93\u5165\u4EFB\u52A1\u5185\u5BB9\uFF0C\u6309 Enter \u952E\u6DFB\u52A0\uFF08Shift+Enter \u6362\u884C\uFF09",
          cls: "todo-input"
        });
        const linkRow = inputSection.createEl("div", { cls: "todo-input-row" });
        linkRow.createEl("label", { text: "\u94FE\u63A5\uFF08\u53EF\u9009\uFF09\uFF1A", cls: "todo-input-label" });
        this.taskLink = linkRow.createEl("input", {
          type: "text",
          placeholder: "https://...",
          cls: "todo-link-input"
        });
        const dateRow = inputSection.createEl("div", { cls: "todo-input-row todo-input-row-with-date" });
        dateRow.style.cursor = "pointer";
        dateRow.createEl("label", { text: "\u622A\u6B62\u65E5\u671F\uFF08\u53EF\u9009\uFF09\uFF1A", cls: "todo-input-label" });
        this.taskDueDate = dateRow.createEl("input", {
          type: "date",
          cls: "todo-date-input"
        });
        dateRow.addEventListener("click", (e) => {
          if (e.target !== this.taskDueDate) {
            e.stopPropagation();
            setTimeout(() => {
              this.taskDueDate.focus();
              this.taskDueDate.click();
            }, 0);
          }
        }, { signal: this.signal });
        const priorityRow = inputSection.createEl("div", { cls: "todo-input-row" });
        priorityRow.createEl("label", { text: "\u4F18\u5148\u7EA7\uFF08\u53EF\u9009\uFF09\uFF1A", cls: "todo-input-label" });
        this.taskPriority = priorityRow.createEl("select", { cls: "todo-priority-select" });
        this.taskPriority.add(new Option("\u65E0", "none"));
        this.taskPriority.add(new Option("\u9AD8", "high"));
        this.taskPriority.add(new Option("\u4E2D", "medium"));
        this.taskPriority.add(new Option("\u4F4E", "low"));
        const buttonContainer = inputSection.createEl("div", { cls: "todo-input-buttons" });
        buttonContainer.createEl("button", {
          text: "\u6DFB\u52A0",
          cls: "todo-add-button"
        }).addEventListener("click", () => this.addTasks(), { signal: this.signal });
        buttonContainer.createEl("button", {
          text: "\u6E05\u7A7A",
          cls: "todo-clear-button"
        }).addEventListener("click", () => {
          this.taskInput.value = "";
          this.taskLink.value = "";
          this.taskDueDate.value = "";
          this.taskPriority.value = "none";
        }, { signal: this.signal });
        this.taskInput.addEventListener("keydown", (e) => {
          if (e.key === "Enter" && !e.shiftKey) {
            e.preventDefault();
            this.addTasks();
          }
        }, { signal: this.signal });
        this.taskInput.addEventListener("input", () => {
          this.taskInput.style.height = "auto";
          this.taskInput.style.height = Math.min(this.taskInput.scrollHeight, 200) + "px";
        }, { signal: this.signal });
        this.setupEventDelegation(this.signal);
        this.setupDragDelegation();
        this.todoContainer.addEventListener("dblclick", (e) => {
          const content = e.target.closest(".todo-content");
          if (!content) return;
          const card = content.closest(".todo-card");
          if (!card) return;
          const taskId = card.dataset.taskId;
          const task = this.plugin.findTaskById(taskId);
          if (task) {
            this.showEditDialog(task, card);
          }
        }, { signal: this.signal });
        this.renderTasks();
      }
      setupEventDelegation(signal) {
        this.todoContainer.addEventListener("click", (e) => {
          const card = e.target.closest(".todo-card");
          if (!card) return;
          if (e.target.type === "checkbox") {
            this.handleTaskComplete(card.dataset.taskId, e.target.checked);
          }
          if (e.target.classList.contains("todo-delete-button")) {
            this.handleTaskDelete(card.dataset.taskId);
          }
        }, { signal });
        this.todoContainer.addEventListener("contextmenu", (e) => {
          const card = e.target.closest(".todo-card");
          if (!card) return;
          e.preventDefault();
          const taskId = card.dataset.taskId;
          this.showReminderMenu(e, taskId);
        }, { signal });
      }
      // 容器级别拖拽委托 —— 替代逐卡片绑定
      setupDragDelegation() {
        if (!this.todoContainer) return;
        this.todoContainer.addEventListener("dragstart", (e) => {
          const card = e.target.closest(".todo-card");
          if (!card) return;
          card.classList.add("todo-card-dragging");
          this._dragState = { taskId: card.dataset.taskId, sourceContainer: card.parentElement, sourceDate: card.dataset.date };
          e.dataTransfer.setData("text/plain", card.dataset.taskId);
          e.dataTransfer.effectAllowed = "move";
        }, { signal: this.signal });
        this.todoContainer.addEventListener("dragend", (e) => {
          const card = e.target.closest(".todo-card");
          if (card) card.classList.remove("todo-card-dragging");
          this._dragState = null;
        }, { signal: this.signal });
        this.todoContainer.addEventListener("dragover", (e) => {
          e.preventDefault();
          e.dataTransfer.dropEffect = "move";
          const draggingCard = this.todoContainer.querySelector(".todo-card-dragging");
          const targetCard = e.target.closest(".todo-card");
          if (!draggingCard || !targetCard || draggingCard === targetCard) return;
          if (draggingCard.parentElement !== targetCard.parentElement) return;
          const rect = targetCard.getBoundingClientRect();
          const midY = rect.top + rect.height / 2;
          const container = targetCard.parentElement;
          if (e.clientY < midY) {
            container.insertBefore(draggingCard, targetCard);
          } else {
            container.insertBefore(draggingCard, targetCard.nextSibling);
          }
        }, { signal: this.signal });
        this.todoContainer.addEventListener("drop", async (e) => {
          e.preventDefault();
          const targetCard = e.target.closest(".todo-card");
          if (!targetCard) return;
          const container = targetCard.parentElement;
          const state = this._dragState;
          if (!state || container !== state.sourceContainer) return;
          if (state.sourceDate) {
            await this.saveTasksOrder(container, state.sourceDate);
          }
        }, { signal: this.signal });
      }
      // 更新卡片内容（不重建 DOM 节点，只更新内容）
      updateCardContent(card, task) {
        var _a;
        const todayStr = formatDate2(/* @__PURE__ */ new Date());
        const isUrgent = isUrgentTask(task, todayStr);
        const content = card.querySelector(".todo-content");
        if (!content) return;
        card.className = `todo-card${task.completed ? " todo-card-completed" : ""}${isUrgent ? " todo-card-urgent" : ""}`;
        card.dataset.completed = task.completed.toString();
        const checkbox = card.querySelector(".todo-checkbox");
        if (checkbox) checkbox.checked = task.completed;
        content.empty();
        if (isUrgent) {
          content.createEl("span", { text: "\u{1F534} \u7D27\u6025", cls: "todo-urgent-badge" });
        }
        if (task.priority) {
          const priorityConfig = getPriorityConfig(task.priority);
          const priorityBadge = content.createEl("span", {
            text: priorityConfig.label,
            cls: "todo-priority-badge"
          });
          priorityBadge.style.backgroundColor = priorityConfig.color + "20";
          priorityBadge.style.color = priorityConfig.color;
        }
        const tags = parseTags(task.content);
        if (tags.length > 0) {
          const tagsContainer = content.createEl("div", { cls: "todo-tags-container" });
          tags.forEach((tag) => {
            const tagEl = tagsContainer.createEl("span", { text: `#${tag}`, cls: "todo-tag" });
            tagEl.addEventListener("click", (e) => {
              e.stopPropagation();
              this.setTagFilter(tag);
            }, { signal: this.signal });
          });
        }
        const textEl = content.createEl("p", { cls: "todo-text" });
        textEl.textContent = removeTags(task.content);
        if (task.dueDate) {
          content.createEl("p", { text: `\u622A\u6B62: ${task.dueDate}`, cls: "todo-due-date" });
        }
        if (task.link) {
          const safeLink = SecurityService2.sanitizeLink(task.link);
          if (safeLink) {
            content.createEl("a", {
              text: "\u6253\u5F00\u94FE\u63A5",
              cls: "todo-link",
              href: safeLink,
              target: "_blank",
              rel: "noopener noreferrer"
            });
          }
        }
        const actions = card.querySelector(".todo-actions");
        if (actions) {
          const existingIcon = actions.querySelector(".todo-reminder-icon");
          if ((_a = this.plugin.reminderService) == null ? void 0 : _a.hasReminder(task.taskId)) {
            const remaining = this.plugin.reminderService.getRemainingTime(task.taskId);
            const mins = Math.ceil(remaining / 6e4);
            if (!existingIcon) {
              const alarmIcon = createEl("span", {
                cls: "todo-reminder-icon",
                text: "\u23F0",
                attr: { "data-task-id": task.taskId, title: `${mins} \u5206\u949F\u540E\u63D0\u9192` }
              });
              actions.insertBefore(alarmIcon, actions.firstChild);
            } else {
              existingIcon.title = `${mins} \u5206\u949F\u540E\u63D0\u9192`;
            }
          } else if (existingIcon) {
            existingIcon.remove();
          }
        }
      }
      async handleTaskComplete(taskId, completed) {
        try {
          const task = this.plugin.findTaskById(taskId);
          if (task) {
            await this.plugin.updateTask(taskId, { ...task, completed });
            if (completed && this.plugin.reminderService) {
              this.plugin.reminderService.cancelReminder(taskId);
            }
            const card = this.todoContainer.querySelector(`.todo-card[data-task-id="${taskId}"]`);
            if (card) {
              this.updateCardContent(card, { ...task, completed });
              const tasksList = card.parentElement;
              if (tasksList) {
                tasksList.appendChild(card);
              }
            }
            this._updateTaskCountBadge();
          }
        } catch (error) {
          this.errorHandler.handle(error, "\u5B8C\u6210\u4EFB\u52A1");
        }
      }
      async handleTaskDelete(taskId) {
        try {
          await this.plugin.deleteTask(taskId);
          const card = this.todoContainer.querySelector(`.todo-card[data-task-id="${taskId}"]`);
          if (card) {
            const tasksList = card.parentElement;
            card.remove();
            if (tasksList && tasksList.children.length === 0) {
              const dateSection = tasksList.closest(".todo-date-section");
              if (dateSection) dateSection.remove();
            }
          }
          this._updateTaskCountBadge();
        } catch (error) {
          this.errorHandler.handle(error, "\u5220\u9664\u4EFB\u52A1");
        }
      }
      async onClose() {
        this.abortController.abort();
        if (this.searchDebounceTimer) {
          clearTimeout(this.searchDebounceTimer);
          this.searchDebounceTimer = null;
        }
        if (this.filterDebounceTimer) {
          clearTimeout(this.filterDebounceTimer);
          this.filterDebounceTimer = null;
        }
      }
      // 添加任务（带输入验证）
      async addTasks() {
        const inputText = this.taskInput.value.trim();
        if (!inputText) return;
        const tasks = inputText.split("\n").filter((task) => task.trim());
        const today = /* @__PURE__ */ new Date();
        const dateStr = formatDate2(today);
        const timeStr = formatDateTime2(today);
        const link = this.taskLink.value.trim() || null;
        const dueDate = this.taskDueDate.value || null;
        const priority = this.taskPriority.value !== "none" ? this.taskPriority.value : null;
        const safeLink = SecurityService2.sanitizeLink(link);
        for (const taskContent of tasks) {
          try {
            const validatedContent = SecurityService2.validateTaskContent(taskContent);
            const newTask = {
              taskId: generateUUID(),
              content: validatedContent,
              completed: false,
              createAt: timeStr,
              link: safeLink,
              dueDate,
              priority
            };
            await this.plugin.addTask(dateStr, newTask);
          } catch (error) {
            this.errorHandler.handle(error, "\u6DFB\u52A0\u4EFB\u52A1");
            return;
          }
        }
        this.taskInput.value = "";
        this.taskLink.value = "";
        this.taskDueDate.value = "";
        this.taskPriority.value = "none";
        this.renderTasks();
      }
      _updateTaskCountBadge() {
        var _a;
        if (!this.taskCountBadge) return;
        const tasks = ((_a = this.plugin.tasksData) == null ? void 0 : _a.tasks) || [];
        let totalTasks = 0, completedTasks = 0;
        for (const dateTask of tasks) {
          const list = dateTask.tasksList || [];
          totalTasks += list.length;
          completedTasks += list.filter((task) => task.completed === true).length;
        }
        this.taskCountBadge.textContent = `\u5DF2\u5B8C\u6210 ${completedTasks} / ${totalTasks}`;
      }
      // 安全解析日期，无效日期返回 null
      _safeParseDate(dateStr) {
        if (!dateStr || typeof dateStr !== "string") return null;
        const d = new Date(dateStr);
        return isNaN(d.getTime()) ? null : d;
      }
      // 渲染任务（diff 模式：只更新变化的卡片，不全量重建 DOM）
      renderTasks() {
        var _a;
        const filter = this.filterSelect.value;
        const today = /* @__PURE__ */ new Date();
        const todayStr = formatDate2(today);
        let filteredTasks = [...this.plugin.tasksData.tasks];
        if (filter === "today") {
          filteredTasks = filteredTasks.filter((task) => task.date === todayStr);
        } else if (filter === "7days") {
          const sevenDaysAgo = new Date(today);
          sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
          filteredTasks = filteredTasks.filter((task) => {
            const taskDate = this._safeParseDate(task.date);
            return taskDate && taskDate >= sevenDaysAgo && taskDate <= today;
          });
        } else if (filter === "30days") {
          const thirtyDaysAgo = new Date(today);
          thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
          filteredTasks = filteredTasks.filter((task) => {
            const taskDate = this._safeParseDate(task.date);
            return taskDate && taskDate >= thirtyDaysAgo && taskDate <= today;
          });
        } else if (filter === "week") {
          const weekStart = getWeekStartDate(today);
          const weekEnd = getWeekEndDate(today);
          filteredTasks = filteredTasks.filter((task) => {
            const taskDate = this._safeParseDate(task.date);
            return taskDate && taskDate >= weekStart && taskDate <= weekEnd;
          });
        }
        const searchKeyword = this.searchInput.value.trim().toLowerCase();
        const priorityFilter = (_a = this.priorityFilterSelect) == null ? void 0 : _a.value;
        const tagFilter = this.currentTagFilter;
        if (searchKeyword || tagFilter || priorityFilter && priorityFilter !== "all") {
          filteredTasks = filteredTasks.map((dateTask) => {
            const filteredTasksList = dateTask.tasksList.filter((task) => {
              if (searchKeyword) {
                const contentMatch = task.content.toLowerCase().includes(searchKeyword);
                const linkMatch = task.link && task.link.toLowerCase().includes(searchKeyword);
                const dueDateMatch = task.dueDate && task.dueDate.includes(searchKeyword);
                if (!contentMatch && !linkMatch && !dueDateMatch) return false;
              }
              if (tagFilter) {
                const tags = parseTags(task.content);
                if (!tags.includes(tagFilter)) return false;
              }
              if (priorityFilter && priorityFilter !== "all") {
                if (priorityFilter === "none") {
                  if (task.priority) return false;
                } else if (task.priority !== priorityFilter) {
                  return false;
                }
              }
              return true;
            });
            return { ...dateTask, tasksList: filteredTasksList };
          }).filter((dateTask) => dateTask.tasksList.length > 0);
        }
        filteredTasks.sort((a, b) => {
          const dateA = this._safeParseDate(a.date);
          const dateB = this._safeParseDate(b.date);
          if (!dateA) return 1;
          if (!dateB) return -1;
          return dateB.getTime() - dateA.getTime();
        });
        this._updateTaskCountBadge();
        if (filteredTasks.length === 0) {
          this.todoContainer.empty();
          const emptyEl = document.createElement("p");
          emptyEl.textContent = "\u6CA1\u6709\u4EFB\u52A1\uFF0C\u6DFB\u52A0\u4E00\u4E2A\u5427\uFF01";
          emptyEl.className = "todo-empty";
          this.todoContainer.appendChild(emptyEl);
          return;
        }
        const existingCards = /* @__PURE__ */ new Map();
        this.todoContainer.querySelectorAll(".todo-card").forEach((card) => {
          existingCards.set(card.dataset.taskId, card);
        });
        const fragment = document.createDocumentFragment();
        for (const dateTask of filteredTasks) {
          const isToday = dateTask.date === todayStr;
          const dateSection = document.createElement("div");
          dateSection.className = `todo-date-section${isToday ? " todo-date-today" : ""}`;
          const dateHeader = document.createElement("div");
          dateHeader.className = "todo-date-header";
          const dateTitle = document.createElement("h3");
          dateTitle.textContent = isToday ? `${dateTask.date} (\u4ECA\u5929)` : dateTask.date;
          dateTitle.className = "todo-date-title";
          dateHeader.appendChild(dateTitle);
          const clearBtn = document.createElement("button");
          clearBtn.textContent = "\u6E05\u7A7A";
          clearBtn.className = "todo-clear-date-button";
          clearBtn.addEventListener("click", async () => {
            if (confirm(`\u786E\u5B9A\u8981\u6E05\u7A7A ${dateTask.date} \u7684\u6240\u6709\u4EFB\u52A1\u5417\uFF1F`)) {
              try {
                await this.plugin.deleteTasksByDate(dateTask.date);
                this.renderTasks();
              } catch (error) {
                this.errorHandler.handle(error, "\u6E05\u7A7A\u4EFB\u52A1");
              }
            }
          }, { signal: this.signal });
          dateHeader.appendChild(clearBtn);
          dateSection.appendChild(dateHeader);
          const tasksContainer = document.createElement("div");
          tasksContainer.className = "todo-date-tasks";
          const tasksList = document.createElement("div");
          tasksList.className = "todo-tasks-list";
          const reminderService = this.plugin.reminderService;
          const sortedTasks = [...dateTask.tasksList].sort((a, b) => {
            if (a.completed && !b.completed) return 1;
            if (!a.completed && b.completed) return -1;
            const aHasReminder = reminderService == null ? void 0 : reminderService.hasReminder(a.taskId);
            const bHasReminder = reminderService == null ? void 0 : reminderService.hasReminder(b.taskId);
            if (aHasReminder && !bHasReminder) return -1;
            if (!aHasReminder && bHasReminder) return 1;
            const aIsUrgent = isUrgentTask(a, todayStr);
            const bIsUrgent = isUrgentTask(b, todayStr);
            if (aIsUrgent && !bIsUrgent) return -1;
            if (!aIsUrgent && bIsUrgent) return 1;
            const aPriority = getPriorityConfig(a.priority).order;
            const bPriority = getPriorityConfig(b.priority).order;
            if (aPriority !== bPriority) {
              return aPriority - bPriority;
            }
            if (!a.dueDate && b.dueDate) return -1;
            if (a.dueDate && !b.dueDate) return 1;
            if (!a.dueDate && !b.dueDate) return 0;
            return new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime();
          });
          for (const task of sortedTasks) {
            let card = existingCards.get(task.taskId);
            if (card) {
              this.updateCardContent(card, task);
            } else {
              card = this.createTaskCard(tasksList, task, dateTask.date);
            }
            tasksList.appendChild(card);
          }
          tasksContainer.appendChild(tasksList);
          dateSection.appendChild(tasksContainer);
          fragment.appendChild(dateSection);
        }
        this.todoContainer.empty();
        this.todoContainer.appendChild(fragment);
      }
      // 设置标签筛选
      setTagFilter(tag) {
        this.currentTagFilter = tag;
        if (this.tagFilterSection) {
          this.tagFilterSection.style.display = "flex";
          this.tagFilterBadge.textContent = `#${tag}`;
        }
        this.renderTasks();
      }
      // 清除标签筛选
      clearTagFilter() {
        this.currentTagFilter = null;
        if (this.tagFilterSection) {
          this.tagFilterSection.style.display = "none";
        }
        this.renderTasks();
      }
      // 显示编辑对话框
      showEditDialog(task, card) {
        const modal = new EditModal(this.app, this, task, card, this.errorHandler);
        modal.open();
      }
      // 更新任务卡片显示
      updateTaskCard(card, task) {
        const content = card.querySelector(".todo-content");
        const textEl = content.querySelector(".todo-text");
        const dueDateEl = content.querySelector(".todo-due-date");
        const linkEl = content.querySelector(".todo-link");
        textEl.textContent = task.content;
        if (task.dueDate) {
          if (dueDateEl) {
            dueDateEl.textContent = `\u622A\u6B62: ${task.dueDate}`;
          } else {
            const newDueDate = content.createEl("p", {
              text: `\u622A\u6B62: ${task.dueDate}`,
              cls: "todo-due-date"
            });
            if (linkEl) {
              content.insertBefore(newDueDate, linkEl);
            }
          }
        } else if (dueDateEl) {
          dueDateEl.remove();
        }
        const safeLink = SecurityService2.sanitizeLink(task.link);
        if (safeLink) {
          if (linkEl) {
            linkEl.href = safeLink;
          } else {
            content.createEl("a", {
              text: "\u6253\u5F00\u94FE\u63A5",
              cls: "todo-link",
              href: safeLink,
              target: "_blank",
              rel: "noopener noreferrer"
            });
          }
        } else if (linkEl) {
          linkEl.remove();
        }
      }
      // 显示提醒右键菜单
      showReminderMenu(e, taskId) {
        const menu = new Menu();
        const reminderService = this.plugin.reminderService;
        const task = this.plugin.findTaskById(taskId);
        if (!task || !reminderService) return;
        const presets = [
          { label: "10 \u5206\u949F\u540E", ms: 10 * 60 * 1e3 },
          { label: "30 \u5206\u949F\u540E", ms: 30 * 60 * 1e3 },
          { label: "1 \u5C0F\u65F6\u540E", ms: 60 * 60 * 1e3 },
          { label: "3 \u5C0F\u65F6\u540E", ms: 3 * 60 * 60 * 1e3 }
        ];
        menu.addItem((item) => item.setTitle("\u{1F4CB} \u63D0\u9192\u6211").setDisabled(true));
        presets.forEach((preset) => {
          menu.addItem(
            (item) => item.setTitle(preset.label).onClick(() => {
              reminderService.setReminder(taskId, task.content, preset.ms, task.link);
              new Notice(`\u5DF2\u8BBE\u7F6E ${preset.label} \u63D0\u9192`, 3e3);
              this.renderTasks();
            })
          );
        });
        menu.addItem(
          (item) => item.setTitle("\u81EA\u5B9A\u4E49\u65F6\u95F4...").onClick(() => {
            const modal = new Modal(this.app);
            modal.titleEl.setText("\u8BBE\u7F6E\u63D0\u9192\u65F6\u95F4");
            const inputEl = modal.contentEl.createEl("input", {
              type: "number",
              placeholder: "\u8BF7\u8F93\u5165\u5206\u949F\u6570\uFF081-1440\uFF09",
              attr: { min: "1", max: "1440" }
            });
            inputEl.style.width = "100%";
            inputEl.style.padding = "8px";
            inputEl.style.marginTop = "8px";
            inputEl.style.marginBottom = "8px";
            const btnContainer = modal.contentEl.createEl("div");
            btnContainer.style.display = "flex";
            btnContainer.style.gap = "8px";
            btnContainer.style.justifyContent = "flex-end";
            const cancelBtn = btnContainer.createEl("button", { text: "\u53D6\u6D88" });
            cancelBtn.addEventListener("click", () => modal.close());
            const confirmBtn = btnContainer.createEl("button", { text: "\u786E\u5B9A" });
            confirmBtn.style.backgroundColor = "var(--interactive-accent)";
            confirmBtn.style.color = "white";
            confirmBtn.style.border = "none";
            confirmBtn.style.padding = "6px 16px";
            confirmBtn.style.borderRadius = "4px";
            confirmBtn.addEventListener("click", () => {
              const mins = parseInt(inputEl.value, 10);
              if (!inputEl.value || isNaN(mins) || mins < 1 || mins > 1440) {
                new Notice("\u8BF7\u8F93\u5165 1-1440 \u4E4B\u95F4\u7684\u6B63\u6574\u6570", 3e3);
                return;
              }
              reminderService.setReminder(taskId, task.content, mins * 60 * 1e3, task.link);
              new Notice(`\u5DF2\u8BBE\u7F6E ${mins} \u5206\u949F\u540E\u63D0\u9192`, 3e3);
              this.renderTasks();
              modal.close();
            });
            inputEl.addEventListener("keydown", (ev) => {
              if (ev.key === "Enter") confirmBtn.click();
            });
            modal.open();
            inputEl.focus();
          })
        );
        if (reminderService.hasReminder(taskId)) {
          menu.addSeparator();
          const remaining = reminderService.getRemainingTime(taskId);
          const mins = Math.ceil(remaining / 6e4);
          menu.addItem(
            (item) => item.setTitle(`\u23F0 \u53D6\u6D88\u63D0\u9192 (\u5269\u4F59 ${mins} \u5206\u949F)`).onClick(() => {
              reminderService.cancelReminder(taskId);
              new Notice("\u5DF2\u53D6\u6D88\u63D0\u9192", 3e3);
              this.renderTasks();
            })
          );
        }
        menu.showAtPosition({ x: e.clientX, y: e.clientY });
      }
      // 显示导出对话框
      showExportDialog() {
        const modal = new ExportModal(this.app, this);
        modal.open();
      }
      // 导出任务到CSV
      async exportTasksToCSV(startDate, endDate) {
        const start = new Date(startDate);
        const end = new Date(endDate);
        const escapeCSV = (cell) => {
          if (cell === null || cell === void 0) return "";
          const str = String(cell);
          if (str.includes(",") || str.includes("\n") || str.includes('"') || /^[=+\-@\t]/.test(str)) {
            return `"${str.replace(/"/g, '""')}"`;
          }
          return str;
        };
        const filteredTasks = [];
        for (const dateTask of this.plugin.tasksData.tasks) {
          const taskDate = new Date(dateTask.date);
          if (taskDate >= start && taskDate <= end) {
            for (const task of dateTask.tasksList) {
              filteredTasks.push({
                date: dateTask.date,
                content: task.content,
                completed: task.completed ? "\u5DF2\u5B8C\u6210" : "\u672A\u5B8C\u6210",
                dueDate: task.dueDate || "",
                link: task.link || "",
                createAt: task.createAt
              });
            }
          }
        }
        if (filteredTasks.length === 0) {
          new Notice("\u6240\u9009\u65E5\u671F\u8303\u56F4\u5185\u6CA1\u6709\u4EFB\u52A1", 3e3);
          return;
        }
        const headers = ["\u65E5\u671F", "\u4EFB\u52A1\u5185\u5BB9", "\u72B6\u6001", "\u622A\u6B62\u65E5\u671F", "\u94FE\u63A5", "\u521B\u5EFA\u65F6\u95F4"];
        const csvRows = [headers.join(",")];
        for (const task of filteredTasks) {
          const row = [
            escapeCSV(task.date),
            escapeCSV(task.content),
            task.completed,
            escapeCSV(task.dueDate),
            escapeCSV(task.link),
            escapeCSV(task.createAt)
          ];
          csvRows.push(row.join(","));
        }
        const csvContent = "\uFEFF" + csvRows.join("\n");
        const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.setAttribute("href", url);
        link.setAttribute("download", `\u5F85\u529E\u5BFC\u51FA_${startDate}_${endDate}.csv`);
        link.style.visibility = "hidden";
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
      }
      // 创建任务卡片
      createTaskCard(container, task, taskDate) {
        var _a;
        const todayStr = formatDate2(/* @__PURE__ */ new Date());
        const isUrgent = isUrgentTask(task, todayStr);
        const card = container.createEl("div", {
          cls: `todo-card ${task.completed ? "todo-card-completed" : ""} ${isUrgent ? "todo-card-urgent" : ""}`
        });
        card.draggable = true;
        card.dataset.taskId = task.taskId;
        card.dataset.completed = task.completed.toString();
        card.dataset.date = taskDate;
        const checkbox = card.createEl("input", {
          type: "checkbox",
          checked: task.completed,
          cls: "todo-checkbox"
        });
        const content = card.createEl("div", {
          cls: "todo-content"
        });
        if (isUrgent) {
          content.createEl("span", { text: "\u{1F534} \u7D27\u6025", cls: "todo-urgent-badge" });
        }
        if (task.priority) {
          const priorityConfig = getPriorityConfig(task.priority);
          const priorityBadge = content.createEl("span", {
            text: priorityConfig.label,
            cls: "todo-priority-badge"
          });
          priorityBadge.style.backgroundColor = priorityConfig.color + "20";
          priorityBadge.style.color = priorityConfig.color;
        }
        const tags = parseTags(task.content);
        if (tags.length > 0) {
          const tagsContainer = content.createEl("div", { cls: "todo-tags-container" });
          tags.forEach((tag) => {
            const tagEl = tagsContainer.createEl("span", {
              text: `#${tag}`,
              cls: "todo-tag"
            });
            tagEl.addEventListener("click", (e) => {
              e.stopPropagation();
              this.setTagFilter(tag);
            }, { signal: this.signal });
          });
        }
        const textEl = content.createEl("p", { cls: "todo-text" });
        textEl.textContent = removeTags(task.content);
        if (task.dueDate) {
          content.createEl("p", {
            text: `\u622A\u6B62: ${task.dueDate}`,
            cls: "todo-due-date"
          });
        }
        if (task.link) {
          const safeLink = SecurityService2.sanitizeLink(task.link);
          if (safeLink) {
            const linkEl = content.createEl("a", {
              text: "\u6253\u5F00\u94FE\u63A5",
              cls: "todo-link",
              href: safeLink,
              target: "_blank",
              rel: "noopener noreferrer"
            });
          }
        }
        const actions = card.createEl("div", { cls: "todo-actions" });
        if ((_a = this.plugin.reminderService) == null ? void 0 : _a.hasReminder(task.taskId)) {
          const remaining = this.plugin.reminderService.getRemainingTime(task.taskId);
          const mins = Math.ceil(remaining / 6e4);
          actions.createEl("span", {
            cls: "todo-reminder-icon",
            text: "\u23F0",
            attr: { "data-task-id": task.taskId, title: `${mins} \u5206\u949F\u540E\u63D0\u9192` }
          });
        }
        const deleteBtn = actions.createEl("button", {
          text: "\xD7",
          cls: "todo-delete-button"
        });
        deleteBtn.addEventListener("click", async () => {
          try {
            await this.plugin.deleteTask(task.taskId);
            card.remove();
          } catch (error) {
            this.errorHandler.handle(error, "\u5220\u9664\u4EFB\u52A1");
          }
        }, { signal: this.signal });
        return card;
      }
      async saveTasksOrder(container, taskDate) {
        try {
          const cards = container.querySelectorAll(".todo-card");
          const newOrder = [];
          const seenTaskIds = /* @__PURE__ */ new Set();
          cards.forEach((card) => {
            const taskId = card.dataset.taskId;
            if (seenTaskIds.has(taskId)) return;
            seenTaskIds.add(taskId);
            const task = this.plugin.findTaskById(taskId);
            if (task) {
              newOrder.push(task);
            }
          });
          const originalDateTask = this.plugin.tasksData.tasks.find((t) => t.date === taskDate);
          if (originalDateTask) {
            for (const task of originalDateTask.tasksList) {
              if (!seenTaskIds.has(task.taskId)) {
                newOrder.push(task);
              }
            }
          }
          await this.plugin.updateTasksOrder(taskDate, newOrder);
        } catch (error) {
          this.errorHandler.handle(error, "\u4FDD\u5B58\u4EFB\u52A1\u987A\u5E8F");
        }
      }
    };
    module2.exports = TodoView2;
  }
});

// plugin.js
var { Plugin } = require("obsidian");
var path = require("path");
var { formatDate, formatDateTime } = require_date();
var TimerManager = require_TimerManager();
var ErrorHandler = require_ErrorHandler();
var SecurityService = require_SecurityService();
var ReminderService = require_ReminderService();
var TodoView = require_TodoView();
var TodoKanbanPlugin = class extends Plugin {
  constructor(app, manifest) {
    super(app, manifest);
    this.tasksData = { version: "1.2.0", tasks: [], lastModified: (/* @__PURE__ */ new Date()).toISOString() };
    this.taskIdIndex = /* @__PURE__ */ new Map();
    this.dateIndex = /* @__PURE__ */ new Map();
    this.timerManager = new TimerManager();
    this.errorHandler = new ErrorHandler(require("obsidian").Notice);
    this.reminderService = null;
    this._dailyTimerId = null;
  }
  buildIndexes() {
    this.taskIdIndex.clear();
    this.dateIndex.clear();
    for (const dateTask of this.tasksData.tasks || []) {
      if (!dateTask || !Array.isArray(dateTask.tasksList) || !dateTask.date) continue;
      this.dateIndex.set(dateTask.date, dateTask);
      for (const task of dateTask.tasksList) {
        if (!task || !task.taskId) continue;
        this.taskIdIndex.set(task.taskId, { date: dateTask.date, task });
      }
    }
  }
  // 优化后的findTaskById使用索引查找
  findTaskById(taskId) {
    const indexed = this.taskIdIndex.get(taskId);
    return indexed ? indexed.task : null;
  }
  migrateData(oldData) {
    if (!oldData.version) {
      return {
        version: "1.2.0",
        tasks: oldData.tasks || [],
        lastModified: (/* @__PURE__ */ new Date()).toISOString()
      };
    }
    if (oldData.version === "1.1.0") {
      for (const dateTask of oldData.tasks) {
        for (const task of dateTask.tasksList) {
          if (!task.hasOwnProperty("priority")) {
            task.priority = null;
          }
        }
      }
      oldData.version = "1.2.0";
      oldData.lastModified = (/* @__PURE__ */ new Date()).toISOString();
    }
    return oldData;
  }
  async onload() {
    this.tasksFilePath = path.join(this.manifest.dir, "tasks.json");
    await this.loadTasks();
    this.reminderService = new ReminderService(this.timerManager, this);
    await this.inheritIncompleteTasks();
    this.setupDailyInheritTimer();
    this.registerView("todo-kanban-view", (leaf) => new TodoView(leaf, this, this.errorHandler));
    this.addRibbonIcon("check-square", "\u5F85\u529E\u770B\u677F", () => {
      this.activateView("todo-kanban-view");
    });
  }
  onunload() {
    this.timerManager.clearAll();
    if (this.reminderService) {
      this.reminderService.clearAll();
    }
    this.app.workspace.detachLeavesOfType("todo-kanban-view");
  }
  async activateView(viewType) {
    let leaf;
    for (const l of this.app.workspace.getLeavesOfType(viewType)) {
      leaf = l;
      break;
    }
    if (!leaf) {
      leaf = this.app.workspace.getRightLeaf(false);
      await leaf.setViewState({
        type: viewType,
        active: true
      });
    }
    this.app.workspace.revealLeaf(leaf);
  }
  async loadTasks() {
    try {
      const exists = await this.app.vault.adapter.exists(this.tasksFilePath);
      if (exists) {
        const data = await this.app.vault.adapter.read(this.tasksFilePath);
        let parsedData = JSON.parse(data);
        parsedData = this.migrateData(parsedData);
        this.tasksData = parsedData;
      } else {
        this.tasksData = { version: "1.2.0", tasks: [], lastModified: (/* @__PURE__ */ new Date()).toISOString() };
        await this.saveTasks();
      }
      this.buildIndexes();
    } catch (error) {
      this.errorHandler.handle(error, "\u52A0\u8F7D\u4EFB\u52A1\u6570\u636E");
      this.tasksData = { version: "1.2.0", tasks: [], lastModified: (/* @__PURE__ */ new Date()).toISOString() };
      this.buildIndexes();
    }
  }
  async saveTasks() {
    try {
      this.tasksData.lastModified = (/* @__PURE__ */ new Date()).toISOString();
      await this.app.vault.adapter.write(this.tasksFilePath, JSON.stringify(this.tasksData, null, 2));
      this.buildIndexes();
    } catch (error) {
      this.errorHandler.handle(error, "\u4FDD\u5B58\u4EFB\u52A1\u6570\u636E");
      throw error;
    }
  }
  // 启动时备份任务数据
  async backupTasks() {
    try {
      const backupPath = this.tasksFilePath.replace(".json", "-backup.json");
      await this.app.vault.adapter.write(backupPath, JSON.stringify(this.tasksData, null, 2));
    } catch (error) {
      console.error("Backup failed:", error);
    }
  }
  // 自动继承历史未完成任务到今天（移动而非复制）
  // 返回是否有变化
  async inheritIncompleteTasks() {
    const today = /* @__PURE__ */ new Date();
    const todayStr = formatDate(today);
    const timeStr = formatDateTime(today);
    const existingTodayTask = this.tasksData.tasks.find((t) => t.date === todayStr);
    const existingTodayTasks = existingTodayTask ? [...existingTodayTask.tasksList] : [];
    const todayTaskIds = new Set(existingTodayTasks.map((t) => t.taskId));
    const movedTasks = [];
    const remainingHistory = [];
    for (const dateTask of this.tasksData.tasks) {
      if (dateTask.date === todayStr) continue;
      const completedTasks = dateTask.tasksList.filter((task) => task.completed);
      const incompleteTasks = dateTask.tasksList.filter((task) => !task.completed);
      for (const task of incompleteTasks) {
        if (!todayTaskIds.has(task.taskId)) {
          movedTasks.push({ ...task, createAt: timeStr });
        }
      }
      if (completedTasks.length > 0) {
        remainingHistory.push({ ...dateTask, tasksList: completedTasks });
      }
    }
    const hasChanges = movedTasks.length > 0;
    if (!hasChanges) return false;
    const newTodayTask = {
      date: todayStr,
      createTime: existingTodayTask ? existingTodayTask.createTime : timeStr,
      tasksList: [...existingTodayTasks, ...movedTasks]
    };
    const newTasksData = {
      ...this.tasksData,
      tasks: [newTodayTask, ...remainingHistory]
    };
    const oldTasksData = this.tasksData;
    this.tasksData = newTasksData;
    try {
      await this.saveTasks();
    } catch (error) {
      this.tasksData = oldTasksData;
      this.buildIndexes();
      throw error;
    }
    return true;
  }
  setupDailyInheritTimer() {
    const now = /* @__PURE__ */ new Date();
    const target = new Date(now);
    target.setHours(1, 0, 0, 0);
    if (now >= target) {
      target.setDate(target.getDate() + 1);
    }
    const delay = target.getTime() - now.getTime();
    if (this._dailyTimerId != null) {
      clearTimeout(this._dailyTimerId);
    }
    this._dailyTimerId = this.timerManager.setTimeout(async () => {
      const hasChanges = await this.inheritIncompleteTasks();
      if (hasChanges) {
        this.notifyViewsToRefresh();
      }
      this.setupDailyInheritTimer();
    }, delay);
  }
  // 通知所有待办视图刷新
  notifyViewsToRefresh() {
    const leaves = this.app.workspace.getLeavesOfType("todo-kanban-view");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view && view.renderTasks) {
        view.renderTasks();
      }
    }
  }
  async addTask(date, task) {
    SecurityService.validateTaskContent(task.content);
    let dateTask = this.tasksData.tasks.find((t) => t.date === date);
    if (!dateTask) {
      dateTask = {
        date,
        createTime: task.createAt,
        tasksList: []
      };
      this.tasksData.tasks.push(dateTask);
    }
    dateTask.tasksList.push(task);
    await this.saveTasks();
  }
  // 根据日期获取任务
  getTasksByDate(date) {
    return this.tasksData.tasks.find((t) => t.date === date);
  }
  async updateTasksOrder(date, newOrder) {
    const dateTask = this.tasksData.tasks.find((t) => t.date === date);
    if (dateTask) {
      dateTask.tasksList = newOrder;
      await this.saveTasks();
    }
  }
  async updateTask(taskId, updatedTask) {
    const indexed = this.taskIdIndex.get(taskId);
    if (!indexed) return;
    const { date } = indexed;
    const dateTask = this.dateIndex.get(date);
    if (!dateTask) return;
    const taskIndex = dateTask.tasksList.findIndex((t) => t.taskId === taskId);
    if (taskIndex === -1) return;
    SecurityService.validateTaskContent(updatedTask.content);
    const safeLink = SecurityService.sanitizeLink(updatedTask.link);
    const validPriorities = ["high", "medium", "low", null, void 0];
    if (!validPriorities.includes(updatedTask.priority)) {
      throw new Error(`\u65E0\u6548\u7684\u4F18\u5148\u7EA7: ${updatedTask.priority}`);
    }
    if (updatedTask.dueDate != null && !/^\d{4}-\d{2}-\d{2}$/.test(updatedTask.dueDate)) {
      throw new Error(`\u65E0\u6548\u7684\u622A\u6B62\u65E5\u671F\u683C\u5F0F: ${updatedTask.dueDate}`);
    }
    dateTask.tasksList[taskIndex] = {
      taskId: updatedTask.taskId,
      content: updatedTask.content,
      completed: updatedTask.completed,
      createAt: updatedTask.createAt,
      link: safeLink,
      dueDate: updatedTask.dueDate,
      priority: updatedTask.priority
    };
    await this.saveTasks();
  }
  async deleteTask(taskId) {
    const indexed = this.taskIdIndex.get(taskId);
    if (!indexed) return;
    const { date } = indexed;
    const dateTask = this.dateIndex.get(date);
    if (!dateTask) return;
    const taskIndex = dateTask.tasksList.findIndex((t) => t.taskId === taskId);
    if (taskIndex === -1) return;
    dateTask.tasksList.splice(taskIndex, 1);
    if (this.reminderService) {
      this.reminderService.cancelReminder(taskId);
    }
    if (dateTask.tasksList.length === 0) {
      const dateTaskIndex = this.tasksData.tasks.findIndex((t) => t.date === dateTask.date);
      if (dateTaskIndex !== -1) {
        this.tasksData.tasks.splice(dateTaskIndex, 1);
      }
    }
    await this.saveTasks();
  }
  // 根据日期删除所有任务
  async deleteTasksByDate(date) {
    const dateTaskIndex = this.tasksData.tasks.findIndex((t) => t.date === date);
    if (dateTaskIndex !== -1) {
      const dateTask = this.tasksData.tasks[dateTaskIndex];
      if (this.reminderService) {
        for (const task of dateTask.tasksList) {
          this.reminderService.cancelReminder(task.taskId);
        }
      }
      this.tasksData.tasks.splice(dateTaskIndex, 1);
      await this.saveTasks();
    }
  }
  // 移动任务到今天（使用索引优化查找）
  async moveTaskToToday(taskId) {
    const today = /* @__PURE__ */ new Date();
    const todayStr = formatDate(today);
    const timeStr = formatDateTime(today);
    const indexed = this.taskIdIndex.get(taskId);
    if (!indexed) return;
    const { date: sourceDate } = indexed;
    const sourceDateTask = this.dateIndex.get(sourceDate);
    if (!sourceDateTask) return;
    const taskIndex = sourceDateTask.tasksList.findIndex((t) => t.taskId === taskId);
    if (taskIndex === -1) return;
    const [taskToMove] = sourceDateTask.tasksList.splice(taskIndex, 1);
    if (sourceDateTask.tasksList.length === 0) {
      const dateTaskIndex = this.tasksData.tasks.findIndex((t) => t.date === sourceDateTask.date);
      if (dateTaskIndex !== -1) {
        this.tasksData.tasks.splice(dateTaskIndex, 1);
      }
    }
    let todayTask = this.tasksData.tasks.find((t) => t.date === todayStr);
    if (!todayTask) {
      todayTask = {
        date: todayStr,
        createTime: timeStr,
        tasksList: []
      };
      this.tasksData.tasks.push(todayTask);
    }
    todayTask.tasksList.push(taskToMove);
    await this.saveTasks();
  }
};
module.exports = TodoKanbanPlugin;
